services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"    # Map host 443 to container 443
      - "80:80"      # Map host 80 to container 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount Nginx config
      - ./certs:/etc/nginx/certs:ro            # Mount self-signed certificates
    restart: unless-stopped
