from __future__ import annotations

from .engine import run_dda_matrix
from .scalar import (
    DEFAULT_DELAYS,
    DEFAULT_DERIVATIVE_POINTS,
    DEFAULT_MODEL_TERMS,
    DEFAULT_NR_TAU,
    DEFAULT_ORDER,
    DEFAULT_WINDOW_LENGTH,
    DEFAULT_WINDOW_STEP,
    DDAResult,
    DDAVariantResult,
    DerivativeDDA,
    PointwiseDesignMatrix,
    ScalarDerivativeMode,
    ScalarRegressionMode,
    WeakFormDDA,
    WeakFormDesignMatrix,
    WeakQuadratureRule,
    build_pointwise_design_matrix,
    build_weak_form_design_matrix,
    default_integration_window,
)
from .sparse import (
    GroupLassoResult,
    SparseAdditiveDesignMatrix,
    SparseAdditiveStabilityResult,
    SparseAdditiveWeakFormDDA,
    build_sparse_additive_weak_form_design_matrix,
    build_sparse_additive_weak_form_design_matrix_for_trajectories,
    compute_delay_block_condition_numbers,
    compute_delay_block_correlation,
    compute_state_coverage,
    fit_group_lasso,
    stability_select_sparse_additive_weak_form,
    thin_candidate_delays_by_collinearity,
)

__all__ = [
    "DEFAULT_DELAYS",
    "DEFAULT_DERIVATIVE_POINTS",
    "DEFAULT_MODEL_TERMS",
    "DEFAULT_NR_TAU",
    "DEFAULT_ORDER",
    "DEFAULT_WINDOW_LENGTH",
    "DEFAULT_WINDOW_STEP",
    "DDAResult",
    "DDAVariantResult",
    "DerivativeDDA",
    "GroupLassoResult",
    "PointwiseDesignMatrix",
    "ScalarDerivativeMode",
    "ScalarRegressionMode",
    "SparseAdditiveDesignMatrix",
    "SparseAdditiveStabilityResult",
    "SparseAdditiveWeakFormDDA",
    "WeakFormDDA",
    "WeakFormDesignMatrix",
    "WeakQuadratureRule",
    "build_pointwise_design_matrix",
    "build_sparse_additive_weak_form_design_matrix",
    "build_sparse_additive_weak_form_design_matrix_for_trajectories",
    "build_weak_form_design_matrix",
    "compute_delay_block_condition_numbers",
    "compute_delay_block_correlation",
    "compute_state_coverage",
    "default_integration_window",
    "fit_group_lasso",
    "run_dda_matrix",
    "stability_select_sparse_additive_weak_form",
    "thin_candidate_delays_by_collinearity",
]
