# Docker Compose override for web30 development
# Usage: docker-compose -f docker-compose.yml -f docker-compose.web30.yml up -d traefik

services:
  traefik:
    labels:
      # Add web30 as external service
      - "traefik.enable=true"
      # Route to web30 running on host
      - "traefik.http.routers.web30.rule=Host(`localhost`)"
      - "traefik.http.routers.web30.entrypoints=websecure"
      - "traefik.http.routers.web30.tls=true"
      - "traefik.http.routers.web30.service=web30-service"
      # WebSocket support for Next.js HMR
      - "traefik.http.routers.web30-websocket.rule=Host(`localhost`) && PathPrefix(`/_next/webpack-hmr`)"
      - "traefik.http.routers.web30-websocket.entrypoints=websecure"
      - "traefik.http.routers.web30-websocket.tls=true"
      - "traefik.http.routers.web30-websocket.service=web30-service"
      - "traefik.http.routers.web30-websocket.priority=100"
      - "traefik.http.services.web30-service.loadbalancer.server.url=http://host.docker.internal:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"