version: 2.1

executors:
  windows:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium

jobs:
  build-windows:
    executor: windows
    working_directory: ~/project/packages/configmanager
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            nvm install 18
            nvm use 18
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build & publish Windows app
          command: npm run publish:dev:windows

workflows:
  build-and-publish:
    jobs:
      - build-windows