version: 2.1

executors:
  windows:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium

jobs:
  build-windows:
    executor: windows
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            nvm install 18
            nvm use 18
      - run:
          name: Install root dependencies
          command: npm install
      - run:
          name: Build ConfigManager only
          command: |
            cd packages/configmanager
            npm install
            npm run build
      - run:
          name: Verify and Set AWS Credentials
          command: |
            echo "Checking AWS credentials..."
            if ([string]::IsNullOrEmpty($env:AWS_ACCESS_KEY_ID)) {
              echo "ERROR: AWS_ACCESS_KEY_ID is not set"
              exit 1
            }
            if ([string]::IsNullOrEmpty($env:AWS_SECRET_ACCESS_KEY)) {
              echo "ERROR: AWS_SECRET_ACCESS_KEY is not set"
              exit 1
            }
            echo "AWS credentials are set"
          shell: powershell.exe
      - run:
          name: Publish ConfigManager
          command: |
            cd packages/configmanager
            set AWS_DEFAULT_REGION=us-east-1
            npm run publish:dev:win

workflows:
  build-and-publish:
    jobs:
      - build-windows:
          context: aws-credentials
          filters:
            branches:
              only:
                - main
