[package]
name = "dda-rs"
version = "0.1.3"
edition = "2021"
authors = ["DDALAB Contributors"]
description = "Rust interface for the run_DDA_AsciiEdf binary (Cosmopolitan Libc APE) for Delay Differential Analysis"
license = "MIT"
repository = "https://github.com/sdraeger/DDALAB"
homepage = "https://github.com/sdraeger/DDALAB/tree/main/packages/dda-rs"
documentation = "https://docs.rs/dda-rs"
keywords = ["dda", "delay-differential", "analysis", "eeg", "time-series"]
categories = ["science", "api-bindings"]
readme = "README.md"

[dependencies]
tokio = { version = "1.48.0", features = ["process", "fs", "io-util", "rt", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
log = "0.4"
thiserror = "2.0.17"
chrono = { version = "0.4", features = ["serde"] }
dirs = "6.0.0"

[dev-dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tokio-test = "0.4"
tempfile = "3"
