[package]
name = "ddalab-broker"
version = "0.1.0"
edition = "2021"
authors = ["DDALAB Team"]
description = "Lightweight sync broker for DDALAB institutional deployments"

[dependencies]
# Web framework
axum = { version = "0.8.6", features = ["ws", "macros"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "trace"] }
tokio = { version = "1.42", features = ["full"] }
hyper = { version = "1.5", features = ["full"] }

# Database
sqlx = { version = "0.8", features = [
	"runtime-tokio",
	"postgres",
	"json",
	"chrono",
	"uuid",
] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# WebSocket
tokio-tungstenite = "0.28"
futures-util = "0.3"

# Utilities
uuid = { version = "1.11", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
parking_lot = "0.12"
anyhow = "1.0"
thiserror = "2.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Async traits
async-trait = "0.1"

[lib]
name = "ddalab_broker"
path = "src/lib.rs"

[[bin]]
name = "ddalab-broker"
path = "src/main.rs"
